name: Release Existing APK

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Read versionName from build.gradle.kts
      id: version
      run: |
        version=$(grep 'versionName' app/build.gradle.kts | head -1 | sed -E 's/.*versionName\s*=\s*"(.+)"$/\1/')
        echo "version_name=$version" >> "$GITHUB_OUTPUT"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.version_name }}
        name: v${{ steps.version.outputs.version_name }}
        body: ${{ github.event.head_commit.message }}
        files: app/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
